[package]
name = "rusteze"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.8"
serde = "1"
serde_json = "1"
regex = "1"
itertools = "0.9"
once_cell = "1"
rand = "0.7"
parking_lot = "0.11"
aho-corasick = "0.7"

[profile.release]
codegen-units = 1
