[package]
name = "rusteze"
version = "0.1.0"
authors = ["Mendess2526 <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.6.x"
serde = "1.0.x"
serde_json = "1.0.x"
regex = "1"
itertools = "0.8.x"
once_cell = "1.2.x"

[profile.release]
codegen-units = 1
